artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/krishnaik06/datasets/raw/refs/heads/main/winequality-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_directory: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv
  STATUS_FILE: artifacts/data_validation/statuses.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/winequality-red.csv

model_training:
  root_dir: artifacts/model_training
  training_data: artifacts/data_transformation/Train.csv
  testing_data: artifacts/data_transformation/test.csv
  model_name: model.joblib                                #we are saving our model after training in joblib format(serialization-pkl or joblib)
  


